servers:
  - host: 192.168.1.10
    type: ssh
    user: admin
    key_path: ~/.ssh/id_rsa
    port: 22
  - host: windows-server.example.com
    type: winrm
    user: Administrator
    password: YourPassword
    port: 5985
